apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: gateway
data:
  config.yaml: |
    domain: gateway-ratelimit
    descriptors:
      - key: generic_key
        rate_limit:
          unit: minute
          requests_per_unit: 100

