apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svc-gateway
  namespace: gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: svc-gateway
  namespaceSelector:
    matchNames: ["exchange"]
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
