apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-gateway
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  hosts: ["api.exchange.example.com"]
  gateways: ["public-gateway"]
  http:
    - match: [{ uri: { prefix: "/api/v1/trade" } }]
      route:
        - destination:
            host: svc-trading-api.exchange.svc.cluster.local
            port: { number: 8080 }
    - match: [{ uri: { prefix: "/api/v1/wallet" } }]
      route:
        - destination:
            host: svc-wallet.exchange.svc.cluster.local
            port: { number: 8080 }
